server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway

# Service registry for API Gateway
gateway:
  services:
    - name: auth-service
      publicEndpoints:
        - "/api/v*/auth/login"
        - "/api/v*/public/**"
        - "/public/**"
    - name: service-1
      publicEndpoints:
        - "/api/v*/public/**"
        - "/public/**"
    - name: service-2
      publicEndpoints:
        - "/api/v*/public/**"
        - "/public/**"
    - name: service-3
      publicEndpoints:
        - "/api/v*/public/**"
        - "/public/**"
    - name: logging-service
      publicEndpoints:
        - "/api/v*/public/**"
    - name: messaging-service
      publicEndpoints:
        - "/api/v*/public/**"
