server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway
  
  # Redis configuration inherited from global application.yml
  # Uses Vault secrets: ${redis.password}
  
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${AUTH_SERVICE_URL:http://auth-service:8081}
              predicates:
                - Path=/auth-service/**
              filters:
                - StripPrefix=1
            - id: service-1
              uri: ${SERVICE1_URL:http://service-1:8082}
              predicates:
                - Path=/service-1/**
              filters:
                - StripPrefix=1
            - id: service-2
              uri: ${SERVICE2_URL:http://service-2:8083}
              predicates:
                - Path=/service-2/**
              filters:
                - StripPrefix=1
            - id: service-3
              uri: ${SERVICE3_URL:http://service-3:8084}
              predicates:
                - Path=/service-3/**
              filters:
                - StripPrefix=1
            - id: logging-service
              predicates:
                - Path=/logging/**
              uri: ${LOGGING_SERVICE_URL:http://logging-service:8085}
              filters:
                - StripPrefix=1
            # Messaging Service Route
            - id: messaging-service
              predicates:
                - Path=/messaging/**
              uri: ${MESSAGING_SERVICE_URL:http://messaging-service:8086}
              filters:
                - StripPrefix=1

# Service registry for API Gateway - comma-separated string format
gateway:
  public-paths: "/actuator/health,/actuator/info,/auth-service/api/v*/auth/login,/auth-service/api/v*/public/**,/auth-service/public/**,/service-1/api/v*/public/**,/service-1/public/**,/service-2/api/v*/public/**,/service-2/public/**,/service-3/api/v*/public/**,/service-3/public/**,/logging-service/api/v*/public/**,/messaging-service/api/v*/public/**,/api/v*/auth/login,/api/v*/public/**,/public/**"
  service-names:
    - "auth-service"
    - "service-1"
    - "service-2"
    - "service-3"
    - "logging-service"
    - "messaging-service"
