spring:
  cloud:
    vault:
      enabled: false  # Disable Vault completely for local development

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.security: DEBUG
