# Global configuration shared by all services
spring:
  cloud:
    vault:
      enabled: ${VAULT_ENABLED:false}
      host: ${SPRING_CLOUD_VAULT_HOST:vault}
      port: ${SPRING_CLOUD_VAULT_PORT:8200}
      scheme: ${SPRING_CLOUD_VAULT_SCHEME:http}
      authentication: TOKEN
      token: ${SPRING_CLOUD_VAULT_TOKEN:myroot}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI:http://localhost:8081/}

# Common Eureka client configuration
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}

# Basic actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info
