spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI:http://localhost:8081/}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}

management:
  endpoint:
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true   # Enable liveness/readiness
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui
  # springdoc config above; removed misplaced health.probes (moved under management)
