# Development environment overrides
spring:
  cloud:
    vault:
      enabled: true  # Enable Vault in production
      host: ${SPRING_CLOUD_VAULT_HOST:vault}
      port: ${SPRING_CLOUD_VAULT_PORT:8200}
      scheme: ${SPRING_CLOUD_VAULT_SCHEME:http}
      authentication: TOKEN
      token: ${SPRING_CLOUD_VAULT_TOKEN:myroot}

# Expose all actuator endpoints for debugging in development
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Enable debug logging for development
logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.security: DEBUG
