# Production environment overrides
spring:
  cloud:
    vault:
      enabled: true  # Enable Vault in production
      host: ${SPRING_CLOUD_VAULT_HOST:vault}
      port: ${SPRING_CLOUD_VAULT_PORT:8200}
      scheme: ${SPRING_CLOUD_VAULT_SCHEME:http}
      authentication: TOKEN
      token: ${SPRING_CLOUD_VAULT_TOKEN:myroot}

# Minimal actuator endpoints for production
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never  # Hide details in production

# Production logging - errors and warnings only
logging:
  level:
    org.springframework.cloud: WARN
    org.springframework.security: WARN
    org.apache.tomcat: WARN
    org.apache.coyote: WARN
