# Development environment overrides
spring:
  cloud:
    vault:
      enabled: false  # Disable Vault in dev - use local configs

# Expose all actuator endpoints for debugging in development
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
