# Development environment overrides
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.example: DEBUG
    io.github.resilience4j: DEBUG

# Health endpoint details available for everyone in development
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Development CORS settings - use environment variables
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080,http://localhost:3001}

# Relaxed resilience settings for development
resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 70
        wait-duration-in-open-state: 10s
        sliding-window-size: 5
