# Development environment configuration
# Note: spring.profiles.active should not be set in profile-specific files

# More detailed logging for development
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.example: DEBUG
    io.github.resilience4j: DEBUG

# Health endpoint details available for everyone in development
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Development CORS settings - more permissive
cors:
  allowed-origins: "http://localhost:3000,http://localhost:8080,http://localhost:3001"

# Enable debug mode for development
debug: true
