# Production environment configuration
# Note: spring.profiles.active should not be set in profile-specific files

# Production logging - less verbose, focused on errors and warnings
logging:
  level:
    root: WARN
    com.example: INFO
    org.springframework.security: WARN
    io.github.resilience4j: INFO

# More restrictive CORS for production
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://example.com}

# Health endpoint security for production
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never

# Stricter resilience settings for production
resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 40
        wait-duration-in-open-state: 60s
        sliding-window-size: 20
        minimum-number-of-calls: 10
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 2s
        exponential-backoff-multiplier: 3
  timelimiter:
    configs:
      default:
        timeout-duration: 2s
