spring:
  cloud:
    vault:
      enabled: false  # Disable Vault for local development

eureka:
  client:
    serviceUrl:
      # Use container hostname (fallback) instead of localhost so clients in Docker can reach Eureka
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://discovery-service:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.security: DEBUG
  file:
    name: ${LOG_PATH:logs}/${SERVICE_NAME:app}.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
