server:
  port: ${SERVER_PORT:8085}

spring:
  application:
    name: logging-service
  cloud:
    stream:
      bindings:
        log-input:
          destination: logs.structured
          group: logging-service
          consumer:
            auto-startup: true
        log-output:
          destination: logs.structured
      rabbit:
        bindings:
          log-input:
            consumer:
              auto-bind-dlq: true
              durableSubscription: true
              acknowledge-mode: auto
        default:
          consumer:
            auto-declare: true
            declare-exchange: true
            declare-queue: true
          producer:
            auto-declare: true
            declare-exchange: true

# Logging service configuration
logging:
  level:
    org.springframework.amqp: INFO
    org.apache.http: WARN
    org.springframework.cloud.consul: WARN
    com.ecwid.consul: INFO
  ingestion:
    queue:
      capacity: 5000
    rate:
      single:
        permitsPerSecond: 200
      batch:
        permitsPerSecond: 50
    drain:
      interval:
        ms: 2000
  
  export:
    file:
      directory: ${SHARED_LOG_PATH:-./logs}/aggregated
      format: json  # Options: json, structured, text
      rotation:
        enabled: true
        maxSizeMB: 100
        maxFiles: 30
      compression:
        enabled: true
