server:
  port: ${SERVER_PORT:8086}

spring:
  application:
    name: logging-service

# Logging service configuration
logging:
  ingestion:
    queue:
      capacity: 5000
    rate:
      single:
        permitsPerSecond: 200
      batch:
        permitsPerSecond: 50
    drain:
      interval:
        ms: 2000
  
  export:
    file:
      directory: ${SHARED_LOG_PATH:-./logs}/aggregated
      format: json  # Options: json, structured, text
      rotation:
        enabled: true
        maxSizeMB: 100
        maxFiles: 30
      compression:
        enabled: true

