server:
  port: 8086

spring:
  application:
    name: logging-service

logging:
  level:
    com.example.loggingservice: INFO
    org.springframework.security: WARN
    org.springframework.cloud.netflix.eureka: INFO
