server:
  port: ${SERVER_PORT:8086}

spring:
  application:
    name: messaging-service

# Messaging service configuration
logging:
  level:
    org.springframework.amqp: INFO
    org.apache.http: WARN
    org.springframework.cloud.netflix.eureka: WARN
    com.netflix.discovery: INFO
