server:
  port: 8085

spring:
  application:
    name: messaging-service

logging:
  level:
    com.example.messagingservice: INFO
    org.springframework.security: WARN
    org.springframework.cloud.netflix.eureka: INFO
