server:
  port: 8083

spring:
  application:
    name: service-2

logging:
  level:
    com.example.service2: INFO
    org.springframework.security: WARN
    org.springframework.cloud.netflix.eureka: INFO
