server:
  port: ${SERVER_PORT:8761}

spring:
  application:
    name: discovery-service
  cloud:
    consul:
      host: ${CONSUL_HOST:consul}
      port: ${CONSUL_PORT:8500}
      discovery:
        register: true
        health-check-interval: 10s
        health-check-timeout: 5s
        health-check-critical-timeout: 30s
        prefer-ip-address: true
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${server.port}