# Development overrides for discovery service
eureka:
  server:
    # Disable self-preservation for development
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
    # Lower renewal threshold for dev with fewer services
    renewal-percent-threshold: 0.3

logging:
  level:
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG

