# Development overrides for discovery service
spring:
  cloud:
    consul:
      discovery:
        # Development-specific settings
        health-check-interval: 5s
        health-check-timeout: 3s
        health-check-critical-timeout: 15s

logging:
  level:
    org.springframework.cloud.consul: DEBUG
    com.ecwid.consul: DEBUG

