# Production configuration for discovery service
spring:
  cloud:
    consul:
      discovery:
        # Production-optimized settings
        health-check-interval: 30s
        health-check-timeout: 10s
        health-check-critical-timeout: 60s
        # Production reliability settings
        prefer-ip-address: true
        query-passing: true

logging:
  level:
    org.springframework.cloud.consul: WARN
    com.ecwid.consul: WARN
