server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: service-1
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888/}
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/service1db}
