server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: service-1
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888/}
  
  # Only service-1 specific configuration here
  # Example: if service-1 needs its own database
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/service1db}
    # Both username and password from Vault: secret/service-1/db/
    username: ${vault.secret.service-1.db.username}
    password: ${vault.secret.service-1.db.password}
