server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: service-1
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888/}
  
  # Database configuration inherited from global application.yml
  # Uses Vault secrets: ${database.username} and ${database.password}
  # Service-specific database name override
  datasource:
    url: jdbc:postgresql://postgres:5432/service1db
